name: elecar
description: An Elecar Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.1.2+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
          weight: 600
        - asset: assets/fonts/Exo-Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Exo-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Exo-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Exo-Bold.ttf
          weight: 800
        - asset: assets/fonts/Exo-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Exo-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Exo-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Exo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Exo-Thin.ttf
          weight: 400
        - asset: assets/fonts/Exo-ThinItalic.ttf
          weight: 400
          style: italic

flutter_icons:
  image_path: assets/images/icon.png
  remove_alpha_ios: true
  android: true
  ios: true

flutter_native_splash:
  color: "#0A0A0B"
  image: assets/images/splash.png
  android: true
  ios: true